In [1]:
from google.colab import userdata
import os
os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')

In [2]:
!kaggle datasets download -d utkarshx27/heart-disease-diagnosis-dataset
! unzip "heart-disease-diagnosis-dataset.zip"

Dataset URL: https://www.kaggle.com/datasets/utkarshx27/heart-disease-diagnosis-dataset
License(s): CC0-1.0
Downloading heart-disease-diagnosis-dataset.zip to /content
  0% 0.00/3.29k [00:00<?, ?B/s]
100% 3.29k/3.29k [00:00<00:00, 6.81MB/s]
Archive:  heart-disease-diagnosis-dataset.zip
  inflating: dataset_heart.csv

# Exercise 1 : Exploratory Data Analysis

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
data = pd.read_csv('dataset_heart.csv')

In [5]:
data.head()

,age,sex,chest pain type,resting blood pressure,serum cholestoral,fasting blood sugar,resting electrocardiographic results,max heart rate,exercise induced angina,oldpeak,ST segment,major vessels,thal,heart disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,2
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,1
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,2
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,1
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,1

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   age                                   270 non-null    int64
 1   sex                                   270 non-null    int64
 2   chest pain type                       270 non-null    int64
 3   resting blood pressure                270 non-null    int64
 4   serum cholestoral                     270 non-null    int64
 5   fasting blood sugar                   270 non-null    int64
 6   resting electrocardiographic results  270 non-null    int64
 7   max heart rate                        270 non-null    int64
 8   exercise induced angina               270 non-null    int64
 9   oldpeak                               270 non-null    float64
 10  ST segment                            270 non-null    int64
 11  major vessels                         270 non-null    int64
 12  thal                                  270 non-null    int64
 13  heart disease                         270 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 29.7 KB

In [7]:
# droping target column
a_data=data.drop(['heart disease'],axis=1)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(a_data,data['heart disease'],test_size=0.2,random_state=42)

In [9]:
x_train.head()

,age,sex,chest pain type,resting blood pressure,serum cholestoral,fasting blood sugar,resting electrocardiographic results,max heart rate,exercise induced angina,oldpeak,ST segment,major vessels,thal
115,49,0,2,134,271,0,0,162,0,0.0,2,0,3
33,59,1,4,170,326,0,2,140,1,3.4,3,0,7
184,53,1,3,130,246,1,2,173,0,0.0,1,3,3
142,50,1,3,140,233,0,0,163,0,0.6,2,1,7
197,54,0,3,110,214,0,0,158,0,1.6,2,0,3

In [10]:
y_train.head()

115    1
33     2
184    1
142    2
197    1
Name: heart disease, dtype: int64

# Exercise 2 : Logistic Regression without Grid Search

In [11]:
!kaggle datasets download -d himanshunakrani/iris-dataset
! unzip "iris-dataset.zip"

Dataset URL: https://www.kaggle.com/datasets/himanshunakrani/iris-dataset
License(s): CC0-1.0
Downloading iris-dataset.zip to /content
  0% 0.00/0.98k [00:00<?, ?B/s]
100% 0.98k/0.98k [00:00<00:00, 1.95MB/s]
Archive:  iris-dataset.zip
  inflating: iris.csv

In [12]:
iris_data=pd.read_csv('iris.csv')

In [13]:
iris_data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
iris_data.value_counts('species')

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [15]:
train_data=iris_data.drop(['species'],axis=1)

In [16]:
x_train,x_test,y_train,y_test=train_test_split(train_data,iris_data['species'],test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

# Exercise 3 : Logistic Regression with Grid Search

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
param_grid = {'C': [0.1, 1, 10], 'penalty': ['l1', 'l2']}
grid_search = GridSearchCV(LogisticRegression(solver='liblinear'), param_grid, cv=5)
grid_search.fit(x_train, y_train)
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Best Parameters:", best_params)
print("Accuracy:", accuracy)

Best Parameters: {'C': 10, 'penalty': 'l1'}
Accuracy: 1.0

# Exercise 4 : SVM without Grid Search

In [21]:
from sklearn.svm import SVC

In [22]:
model = SVC(kernel='rbf', C=1.0, gamma='scale')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

# Exercise 5 : SVM with Grid Search

In [23]:
param_grid = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto']}
grid_search = GridSearchCV(SVC(), param_grid, cv=5)
grid_search.fit(x_train, y_train)
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Best Parameters:", best_params)
print("Accuracy:", accuracy)

Best Parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}
Accuracy: 1.0

# Exercise 6 : XGBoost without Grid Search

In [28]:
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

In [29]:
le=LabelEncoder()
y_train_encoded=le.fit_transform(y_train)
y_test_encoded=le.transform(y_test)

xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3
)
model.fit(x_train, y_train_encoded)
y_pred = model.predict(x_test)
y_pred_original = le.inverse_transform(y_pred)
accuracy = accuracy_score(y_test, y_pred_original)
print("Accuracy:", accuracy)

Accuracy: 1.0


# Exercise 7 : XGBoost with Grid Search

In [30]:
param_grid = {
    'learning_rate': [0.01, 0.1, 0.2],
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 4, 5]
}

grid_search = GridSearchCV(xgb.XGBClassifier(), param_grid, cv=5)
grid_search.fit(x_train, y_train_encoded)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

y_pred = best_model.predict(x_test)
y_pred_original = le.inverse_transform(y_pred)
accuracy = accuracy_score(y_test, y_pred_original)

print("Best Parameters:", best_params)
print("Accuracy:", accuracy)

Best Parameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 200}
Accuracy: 1.0